apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-whoami
spec:
  destination:
    name: ''
    namespace: k8s-whoami
    server: 'https://kubernetes.default.svc'
  source:
    path: dev
    repoURL: 'https://github.com/parthivrmenon/whoami.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true